MeuPrimeiroAsp/Controllers/RepresentanteController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MeuPrimeiroAsp.Data;
using MeuPrimeiroAsp.Models;

namespace MeuPrimeiroAsp.Controllers
{
    public class RepresentanteController : Controller
    {
        private readonly DataContext _context;

        public RepresentanteController(DataContext context)
        {
            _context = context;
        }

        // GET: Representante
        public async Task<IActionResult> Index()
        {
            return View(await _context.Representantes.ToListAsync());
        }

        // GET: Representante/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var representanteModel = await _context.Representantes
                .FirstOrDefaultAsync(m => m.Id == id);
            if (representanteModel == null)
            {
                return NotFound();
            }

            return View(representanteModel);
        }

        // GET: Representante/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Representante/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Nome,RazaoSocial,CPF,CNPJ,Email,Telefone,Celular")] RepresentanteModel representanteModel)
        {
            if (ModelState.IsValid)
            {
                _context.Add(representanteModel);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(representanteModel);
        }

        // GET: Representante/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var representanteModel = await _context.Representantes.FindAsync(id);
            if (representanteModel == null)
            {
                return NotFound();
            }
            return View(representanteModel);
        }

        // POST: Representante/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Nome,RazaoSocial,CPF,CNPJ,Email,Telefone,Celular")] RepresentanteModel representanteModel)
        {
            if (id != representanteModel.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(representanteModel);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!RepresentanteModelExists(representanteModel.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(representanteModel);
        }

        // GET: Representante/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var representanteModel = await _context.Representantes
                .FirstOrDefaultAsync(m => m.Id == id);
            if (representanteModel == null)
            {
                return NotFound();
            }

            return View(representanteModel);
        }

        // POST: Representante/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var representanteModel = await _context.Representantes.FindAsync(id);
            if (representanteModel != null)
            {
                _context.Representantes.Remove(representanteModel);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool RepresentanteModelExists(int id)
        {
            return _context.Representantes.Any(e => e.Id == id);
        }
    }
}

MeuPrimeiroAsp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Titulo"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MeuPrimeiroAsp.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg bg-body-tertiary">
            <div class="container-fluid">
                <a class="navbar-brand" href="#">Navbar</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNavDropdown">
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Cliente" asp-action="Cadastro">Cadastro Cliente</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Dropdown link
                            </a>
                            <ul class="dropdown-menu">
                                <li>
                                    <a class="dropdown-item" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                                </li>
                                <li>
                                    <a class="dropdown-item" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                                </li>
                                <li>
                                    <a class="dropdown-item" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                                </li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - MeuPrimeiroAsp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

MeuPrimeiroAsp/Views/Shared/_MeuLayout.cshtml
<!DOCTYPE html>
<html lang="pt-br">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>@ViewData["Titulo"]</title>
  <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
  <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
  <link rel="stylesheet" href="~/MeuPrimeiroAsp.styles.css" asp-append-version="true" />
</head>
<body>
  <!--inicio header -->
  <header>
    <nav class="navbar navbar-expand-lg bg-primary">
      <div class="container">

        <a class="navbar-brand fw-bold" href="/"><img class="img_logo" src="~/img/logo.png" alt="Alternate Text" /></a>

        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse " id="navbarNavDropdown">
          <ul class="navbar-nav fs-3 ">

            @* Area Com autenticação *@
            @if (User.Identity.IsAuthenticated)
            {
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Selecione o item
                </a>
                <ul class="dropdown-menu">
                  <li>
                    <a class="dropdown-item fw-bold" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                  </li>
                  <li>
                    <a class="dropdown-item fw-bold" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                  </li>
                  <li>
                    <a class="dropdown-item fw-bold" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                  </li>
                </ul>
              </li>

              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle fw-bold" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Representante
                </a>
                <ul class="dropdown-menu">
                  <li>
                    <a class="dropdown-item fw-bold" asp-area="" asp-controller="Representante" asp-action="Index">Todos</a>
                  </li>
                  <li>
                    <a class="dropdown-item fw-bold" asp-area="" asp-controller="Representante" asp-action="Create">Cadastrar</a>
                  </li>
                </ul>
              </li>
            }
          </ul>
        </div>


        <!--area login -->
        <ul class="nav navbar-nav navbar-right fs-3">
          @if (!User.Identity.IsAuthenticated)
          {
            <li>
              <a class="nav-link text-dark fw-bold" asp-route="Usuario.Cadastro">
                <i class="bi bi-person-add fs-3"></i> Cadastre-se
              </a>
            </li>
            <li>
              <a class="nav-link text-dark fw-bold" asp-route="Usuario.Login">
                <i class="bi bi-person-add fs-3"></i> Entre
              </a>
            </li>
          }
          else
          {
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle fw-bold text-uppercase " href="#"
                 role="button" data-bs-toggle="dropdown" aria-expanded="false">
                @User.Identity.Name
              </a>
              <ul class="dropdown-menu">
                <li>
                  <a class="dropdown-item fw-bold" asp-area="" asp-controller="fazer" asp-action="usuario">
                    Dados
                  </a>
                </li>
                <li>
                  <a class="dropdown-item fw-bold" asp-area="" asp-controller="fazer" asp-action="usario">
                    Alterar Senha
                  </a>
                </li>
                <li>
                  <a class="dropdown-item fw-bold" asp-area="" asp-controller="fazer" asp-action="usuario">
                    Quem sou
                  </a>
                </li>
                <li>
                  <a class="dropdown-item fw-bold" asp-route="Usuario.Logout">
                    Sair
                  </a>
                </li>
              </ul>
            </li>
          }
        </ul>
      </div>
    </nav>
  </header>

  <!--fim header -->

  <div class="container ">
    <main role="main" class="pb-3">
      @RenderBody()
    </main>
  </div>
  <footer class="footer">
    <div class="container">
      <div class="row text-center">
        <div class="col-md-4">
          <h5>Parceiros</h5>
          <p>Lista de parceiros importantes.</p>
        </div>
        <div class="col-md-4">
          <h5>Contato</h5>
          <p>Email: contato@exemplo.com</p>
          <p>Telefone: (11) 99999-9999</p>
        </div>
        <div class="col-md-4">
          <h5>Endereço</h5>
          <p>Rua Exemplo, 123</p>
          <p>Cidade, Estado</p>
        </div>
      </div>
    </div>
  </footer>
  <script src="~/lib/jquery/dist/jquery.min.js"></script>
  @* <script src="~/lib/jquery-mask/jquery.mask.min.js"></script> *@
  <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
  <script src="~/js/site.js" asp-append-version="true"></script>
  @await RenderSectionAsync("Scripts", required: false)
</body>
</html>